INSERT INTO pelicula (titol, titol_original, anny, id_nacionalitat, id_genere, durada, edat_recomanada, tipus_color, tipus_so, director, guionista, productor, actors, sinopsis, url_web, url_imatge)
VALUES ('El resplandor', 'The Shining', 1992, 11, 4, '01:45:23', 18, 'Color', 'Dolby Digital 5.1', 'Stanley Kubrick', 'Stanley Kubrick', 'Jeff Cox', '...','Arriben a una casa per a fer-sen carrec...', 'www.theshining.com', 'elresplandor.jpg');
INSERT INTO pelicula (titol, titol_original, anny, id_nacionalitat, id_genere, durada, edat_recomanada, tipus_color, tipus_so, director, guionista, productor, actors, sinopsis, url_web, url_imatge)
VALUES ('Torrente', 'Torrente', 1992, 0, 2, '01:45:23', 10, 'Color', 'Dolby Digital 5.1', 'Santiago Segura', 'Santiago Segura', 'Jeff Cox', '...','Torrente es un policia...', 'www.torrente.com', 'torrente.jpg');
INSERT INTO pelicula (titol, titol_original, anny, id_nacionalitat, id_genere, durada, edat_recomanada, tipus_color, tipus_so, director, guionista, productor, actors, sinopsis, url_web, url_imatge)
VALUES ('Torrente2', 'Torrente2', 1999, 0, 2, '01:55:23', 10, 'Color', 'Dolby Digital 5.1', 'Santiago Segura', 'Santiago Segura', 'Jeff Cox', '...','Torrente es un policia...', 'www.torrente.com', 'torrente2.jpg');
INSERT INTO pelicula (titol, titol_original, anny, id_nacionalitat, id_genere, durada, edat_recomanada, tipus_color, tipus_so, director, guionista, productor, actors, sinopsis, url_web, url_imatge)
VALUES ('Torrente3', 'Torrente3', 2005, 0, 2, '01:32:13', 10, 'Color', 'Dolby Digital 5.1', 'Santiago Segura', 'Santiago Segura', 'Jeff Cox', '...','Torrente es un policia...', 'www.torrente.com', 'torrente3.jpg');
INSERT INTO pelicula (titol, titol_original, anny, id_nacionalitat, id_genere, durada, edat_recomanada, tipus_color, tipus_so, director, guionista, productor, actors, sinopsis, url_web, url_imatge)
VALUES ('12 monos', '12 monkeys', 1995, 11, 6, '01:29:00', 18, 'Color', 'Dolby Digital 5.1', 'Terry Gilliam', 'Chris Marker', 'David Webb', 'Bruce Willis, Brad Pitt, Madeleine Stowe,...','En el futuro la humanidad ha sido mermada por una temible enfermedad. Solamente el diez por ciento de la gente ha sobrevivido, teniendo que habitar por obligacion en el subsuelo. Un preso es elegido para ser explorador, y a cambio de su libertad, el debere viajar al pasado para encontrar a los responsables de la devastadora plaga y dejar un mensaje en un contestador para que los ingenieros de su tiempo futuro solucionen todo el problema', ' ', '12monos.jpg');
INSERT INTO pelicula (titol, titol_original, anny, id_nacionalitat, id_genere, durada, edat_recomanada, tipus_color, tipus_so, director, guionista, productor, actors, sinopsis, url_web, url_imatge)
VALUES ('Abre los ojos', 'Abre los ojos', 1997, 0, 6, '01:57:00', 18, 'Color', 'Dolby Digital 5.1', 'Alejandro Amenabar', 'Alejandro Amenabar', 'MAria Elena Sainz', 'Eduardo Noriega, Penelope Cruz, Chete Lera','Un chico normal y con un talento para las tias sobre la media celebra su cumpleanos y conoce alli a una amiga de su mejor amigo y decide trabajarsela con la escusa de que una novia suya le persigue. A la manana siguiente cuando sale de casa de su nueva amiga, su novia le estaba esperando afuera y al irse con ella en el coche, sufren un accidente en el cual ... ', '', 'abrelosojos.jpg');
INSERT INTO pelicula (titol, titol_original, anny, id_nacionalitat, id_genere, durada, edat_recomanada, tipus_color, tipus_so, director, guionista, productor, actors, sinopsis, url_web, url_imatge)
VALUES ('Mesa para dos', 'Mesa para dos', 2004, 0, 19, '00:11:00', 10, 'Color', 'Dolby Digital 5.1', 'Javier Ercilla', 'Javier Ercilla', 'Jaime Vilalta', 'Juan Diaz, Paz Gomez','Dos desconocidos viajan en autobus, sus miradas se cruzan. Ella baja del autobus, el la sigue y logra invitarla a cenar. Durante la cena las cosas no seren como podia suponerse.', 'www.torrente.com', 'mesapara2.jpg');
INSERT INTO pelicula (titol, titol_original, anny, id_nacionalitat, id_genere, durada, edat_recomanada, tipus_color, tipus_so, director, guionista, productor, actors, sinopsis, url_web, url_imatge)
VALUES ('La mala educacion', 'La mala educacion', 2004, 0, 13, '01:49:00', 18, 'Color', 'Dolby Digital 5.1', 'Pedro Almodovar', 'Pedro Almodovar', 'Agustin Almodovar', 'Gael Garcia Bernal, Javier Camara, Lluis Omar,...','Dos ninos, Ignacio y Enrique, conocen el amor, el cine y el miedo en un colegio religioso a principio de los anos 60. El Padre Manolo, director del colegio y su profesor de literatura es testigo y parte de estos descubrimientos. Los tres personajes vuelven a encontrarse dos veces mes, a final de los anos 70 y en el 80. El reencuentro marcare la vida y la muerte de alguno de ellos', '', 'lamalaeducacion.jpg');
